// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwseomvevwswwojoowag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3c2VvbXZldndzd3dvam9vd2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODY3NTAsImV4cCI6MjA3MjU2Mjc1MH0.hPmDrnH1uI_IVvopGFnuavzY4LhjPo2CMaj2i50-KmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});