// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hznxxhldinmndagwnrpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6bnh4aGxkaW5tbmRhZ3ducnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDYwNTMsImV4cCI6MjA3MjU4MjA1M30.KKKISrY0ox2Ov6biU60BoNJ_FmyEkS5D029_2bV_310";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});