// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqbhaspfyjqzrrzzeakf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxYmhhc3BmeWpxenJyenplYWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjIyNzksImV4cCI6MjA3MjQ5ODI3OX0.LSzhlMUIZ9IUum2B42AfhXA8SbEjfUbkdEh0JEqOMN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});